<a href="https://colab.research.google.com/github/pawlaczyk/data_science_bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.19.5'

# 1. Norma wektora i odległośc punktów

Norma wektora, długośc wektora w R^2

In [5]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [6]:
np.linalg.norm(v1)

4.123105625617661

Norma euklidesowa w R^n

In [7]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

Odległosc dwóch punktów na płaszczyźnie

In [8]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

Odległośc dwóch punktów w przestrzeni R^n

In [9]:
p = np.array([3,0, 1])
q = np.array([0,4, 2])

np.linalg.norm(p-q)

5.0990195135927845

# Mnożenie macierzy

przykład 1

In [10]:
X = np.array([[5,2], [3,9]])
Y= np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 2]
 [3 9]] 

[[ 1]
 [-1]]


In [12]:
Z = np.dot(X,Y)
Z

array([[ 3],
       [-6]])

In [13]:
Z.shape

(2, 1)

przykład 2

In [15]:
X = np.array([ [2, -1, 3],
              [3, 1, 0]])

Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [18]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [19]:
Z.shape

(2, 3)

Wzynacznik macierzy

In [20]:
A = np.array([[2,4], [-1,3]])
np.linalg.det(A)

9.999999999999998

In [21]:
# przybliżenie
round(np.linalg.det(A))

10

Ślad macierzy

In [22]:
A = np.array([[2,4], [-1,3]])
np.trace(A)

5

Macierz jednostkowa

In [23]:
np.eye(5, dtype=int) #domyslnie typ float

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrtona

In [24]:
A = np.array([[2,4], [-1,3]])
A

array([[ 2,  4],
       [-1,  3]])

In [25]:
B = np.linalg.inv(A) # inv skrót od inverse

In [26]:
np.dot(A, B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [27]:
# ustawienia dotyczące printowania
np.set_printoptions(precision=4, suppress=True) # dokłądnosc do 4 , nie trzeba oglądac w notacji matematyczne
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [28]:
np.dot(B,A) #macierze odrtone A*B = B*A = I

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz Tansponowana

In [30]:
A = np.array([[2,4], [-1,3]])
np.transpose(A) 

array([[ 2, -1],
       [ 4,  3]])

In [31]:
# wygodniejsze i częście spotykane rozwiazanie
A.T

array([[ 2, -1],
       [ 4,  3]])

# Rozwiązywanie układów równań

In [32]:
# macierz wpsółczynników
A = np.array([[2, 4],
              [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [37]:
# wektor wyrazów owlnych
B = np.array([[10],
              [-1]])
print(B)

[[10]
 [-1]]


In [38]:
# macierz odwrotna do macieryz A
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [39]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [40]:
X.shape

(2, 1)