<a href="https://colab.research.google.com/github/pawlaczyk/data_science_bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [2]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
price #tablica 3 na 5

array([[  12.4,   12.8,   11.9,   12.6, 1000. ],
       [  12.5,   13. ,   11.7,   12.2, 2000. ],
       [  12.2,   13.4,   12.2,   13.2, 1500. ]])

sum()

In [3]:
price.sum() # suma wszystkich elemntów z tablicy

4650.1

In [5]:
#suma po osi
price.sum(axis=0) # po kolumnie pierwszej 0 os X

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [8]:
price.sum(axis=1) #sumowanie po wierszach oś Y

array([1049.7, 2049.4, 1551. ])

In [7]:
np.sum(price)

4650.1

In [6]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

min()

In [9]:
np.min(price) #minimum z całej tablicy

11.7

In [10]:
#minimum z konkrentej wartosci kolumnowej
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [13]:
np.max(price) #maximum z całej tablicy

2000.0

In [16]:
#maximum z konkrentej wartosci wierszonwej 
np.max(price, axis=1)

array([1000., 2000., 1500.])

median() - mediana

In [17]:
np.median(price)

12.6

mean() średnia

In [18]:
np.mean(price, axis=0) #średnia po kolumnach logniczniej

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

std() odchylenie standardowe logicznie liczyć po kolumnach 

In [19]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

var() - variancja także po kolumnach

In [20]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])

In [21]:
#wyświetlanie bez notacji matematycznej
np.set_printoptions(precision=4, suppress=True)
np.var(price, axis=0) # po kolumnach

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])