<a href="https://colab.research.google.com/github/pawlaczyk/data_science_bootcamp/blob/main/01_wprowadzenie/sekcja_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.19.5'

# 1. Tablice Numpy ndarray

In [ ]:
# metody, atryubuty do wyboru
dir(np)

In [ ]:
# tworzenie tablic
help(np.array)

In [6]:
one_dimensional_array = np.array([1, 3])
one_dimensional_array

array([1, 3])

In [7]:
type(one_dimensional_array)

numpy.ndarray

In [8]:
one_dimensional_array.ndim

1

In [9]:
one_dimensional_array.shape

(2,)

In [10]:
one_dimensional_array.size

2

In [11]:
one_dimensional_array.dtype

dtype('int64')

In [13]:
x2 = np.array([1.3, 2.3, 1.4])

In [15]:
x2

array([1.3, 2.3, 1.4])

In [16]:
x2.dtype

dtype('float64')

##2D tablice

In [18]:
# do sieci neurponowych - wzne posługiwanie się wymiarami
# wiele operacji mnozenie i dodawania - w systuacji gdy od zera tworyzmy sieci neuronowe samiw w bibliotece nupy
d2 = np.array([[1, 2, 3], [4, 2, 1]])

In [21]:
d

array([[ 1,  2],
       [-3,  1]])

In [ ]:
d.ndim

In [20]:
d.shape

(2, 2)

### 3D tablice

In [22]:
# dla danych jak chociażby obraz
e = np.array([
    [[4, 3, 1],
     [3, 2, 1]],

    [[4, 1, 3],
     [4, 2, 1]],

    [[3, 2, 1],
     [4, 3, 2]]
])

In [23]:
e

array([[[4, 3, 1],
        [3, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [24]:
e.ndim

3

In [25]:
e.shape

(3, 2, 3)

# 2. Typy danych

In [26]:
A = np.array([1, 2, 3])

In [27]:
A.dtype

dtype('int64')

In [28]:
# nadawanie typu
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [29]:
# mniej domyslne typu danych
A = np.array([1, 2, 3], dtype='complex')
A.dtype

complex128


In [30]:
#OSTROWZNIE - skonwertuje na typ całkowikty ale tez zmieni wartości!
A = np.array([1.0, 2.2, 3.3], dtype='int')
A.dtype

dtype('int64')

In [31]:
A

array([1, 2, 3])

In [32]:
# typ danych bool logicznych
A = np.array([True, False])
A.dtype

dtype('bool')

In [33]:
# typy danych z tablicy numpy - potrzebne np. gdy chcemy opisywać zdjecie, np piksel jak tablica numpy
# nie chcemy by zajmowało to zbyt dużo miejsca
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
# częsciej używana się unsigned int
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

# 3. Tworzenie ndarray

In [34]:
# Tworzenie tablic NumPy ndarray
# wbudowane funckji, automaztyzacja tworzenia zaawansowanych tablic
x = np.zeros(shape=(4, 10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# np. do masek do zdjeć
x = np.zeros(shape=(4, 10), dtype=int)  # Liczby całkowite
x.dtype

In [35]:
# same jedynkji
x = np.ones(shape=(5, 5))
x = np.ones(shape=(5, 5), dtype=int)

In [ ]:
# 3 bardziej uniwersalna metoda
x = np.full(shape=(3, 3), fill_value=4, dtype=int)

In [36]:
# arrange - wygeneruje dane od 0 do 9 jak range w pythonie
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x = np.arange(start=5, stop=10)  # od do
x

array([5, 6, 7, 8, 9])

In [39]:
x = np.arange(start=5, stop=100, step=10)  # od do (bez 100) krok
print(x) 
x

[ 5 15 25 35 45 55 65 75 85 95]


array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [40]:
x = np.arange(start=100, stop=10, step=-10)  # od do krok ujemny
print(x) 
x

[100  90  80  70  60  50  40  30  20]


array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [41]:
x = np.arange(start=0, stop=1, step=0.05)
print(x)
x

[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [42]:
# .linspace() podobne do arrange
x = np.linspace(start=0, stop=1, num=1)  # ile elementów z tego przedziału które są ROWNO rozlozone
x

array([0.])

In [43]:
# zmienianie kształtu danych
A = np.arange(15)  # <0, 14>
A.reshape(3, 5)  # iloczyn rozmiarów musi dac 115 - ilosc elemntów tablicy
print(A) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [45]:
# automatycznie niech liczy rozmiar
print(A.reshape((3, -1))) # -1 python liczy rozmiar


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [46]:
# automatycznie niech liczy rozmiar
print(A.reshape((-1, 3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# 4. Podstawowe operacje na tablicach

In [49]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print('*'*70)
B

[3 1 4 2]
**********************************************************************


array([ 3, -1,  3,  2])

In [50]:
# dodawanie tablic - rozmiar danych tablic musi sie zgadzac
print(A + B)  # [6 0 7 4]

print(A - B)  # [0 2 1 0]
print(A * B)  # [ 9 -1 12  4]

[6 0 7 4]
[0 2 1 0]
[ 9 -1 12  4]


In [51]:
#dzielenie
# B nie moze zawierać 0
# przy dzieleniu ZAWSZE konwertuje wynik na float
print(A / B)

[ 1.         -1.          1.33333333  1.        ]


In [52]:
# operacje podstawowe ale z numpy metody
np.add(A, B)
np.subtract(A, B)
np.multiply(A, B)
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [53]:
# dodanie stałej do tablicy
print(A + 3)  # [6 4 7 5]
print(2 * A)  #
print(A / 3)  #
print(A + 3 * B)  #

[6 4 7 5]
[6 2 8 4]
[1.         0.33333333 1.33333333 0.66666667]
[12 -2 13  8]


In [56]:
# STANDARDOWE mnożenie macierzowe ALGEBRA LINIOWA
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

In [57]:
# pomnoży elemnt po elemncie
print(X * Y)  # NIE JEST TO MNMOZENIE Z ALGEBRY LINIOWEJ, mniozęnie macierzy nie jest przemienne

[[6 0]
 [2 0]]


In [58]:
print(np.dot(X, Y))  # wiersz * kolumnas

[[  3   6]
 [-12   0]]


In [59]:
print(X.dot(Y))

[[  3   6]
 [-12   0]]


In [60]:
print(X @ Y) # symbol mnoiżenie macierzowe

[[  3   6]
 [-12   0]]


# 5. generowanie liczb pseudolosowych

In [61]:
np.random.seed(0)

In [62]:
r = np.random.randn()  # losowy rozkład normalny
print(r) 

1.764052345967664


In [63]:
r = np.random.randn(10)  # 10 liczblosowy rozkład normalny
print(r)

[ 0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788  0.95008842
 -0.15135721 -0.10321885  0.4105985   0.14404357]


In [64]:
# tablica z 10 wierszy i 4 kolumn, np do histogramów rozkładu normlanego
r = np.random.randn(10, 4)  # przykłądowe dane dla histogramu
print(r)

[[ 1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677 ]
 [-0.85409574 -2.55298982  0.6536186   0.8644362 ]
 [-0.74216502  2.26975462 -1.45436567  0.04575852]
 [-0.18718385  1.53277921  1.46935877  0.15494743]
 [ 0.37816252 -0.88778575 -1.98079647 -0.34791215]
 [ 0.15634897  1.23029068  1.20237985 -0.38732682]
 [-0.30230275 -1.04855297 -1.42001794 -1.70627019]
 [ 1.9507754  -0.50965218 -0.4380743  -1.25279536]
 [ 0.77749036 -1.61389785 -0.21274028 -0.89546656]]


In [65]:
# rozkład jednostajny na przedziale
r = np.random.rand()
print(r)

0.1965823616800535


In [66]:
r = np.random.rand(10, 2)
print(r)

[[0.36872517 0.82099323]
 [0.09710128 0.83794491]
 [0.09609841 0.97645947]
 [0.4686512  0.97676109]
 [0.60484552 0.73926358]
 [0.03918779 0.28280696]
 [0.12019656 0.2961402 ]
 [0.11872772 0.31798318]
 [0.41426299 0.0641475 ]
 [0.69247212 0.56660145]]


In [67]:
r = np.random.randint(10)  # <0, 10)
print(r)  # 1 losowy int

1


In [68]:
r = np.random.randint(low=10, high=101, size=10)  # losowa liczba 2 cyfrowa, size = ile tych liczb


In [69]:
# .choice - losowy elemnt z interowalnego obiektu któy przekazemy
r = np.random.choice([4, 2, 1, 3, 5])

In [70]:
# dane tekstowe
r = np.random.choice(['python', 'java', 'sql'])

In [71]:
data = np.arange(10)
print(data) 

[0 1 2 3 4 5 6 7 8 9]


In [72]:
# przetasowanie danych
np.random.shuffle(data) # jako parametr obiekt który chcemy przetasowac
# OD RAZU ZMIENIA DANE - NIEINTUCYJNE inaczej niż w bibliotece pandas
print(data)

[5 1 4 2 9 7 6 8 0 3]


# 6. Podstawowe funckje

In [73]:
# exponent podstawowa funckja matematyczna - w uczeniu maszynowym czy sieciach neuronowych popularna
np.exp(1)  # stała Eulera
np.sqrt(9)  # pierwsiatke kwadaroawtowy - zawsze float

3.0

In [74]:
# logiczne funckje
# all przechodiz po każdym elmencie iterowalnym i bada czy dany elment zwraca true/false
# jeśli którykolwiek lement jest false to zwraca false
# sposób testowania danych
np.all([2, 3, 4])  # True
np.all([2, 3, 0])  # False

False

In [75]:
# .any sprawdza czy jakikolwiek obiek tjest prawdą
# zastosowanie - czasem szukamy wiersza w którym wysepuje dana wartość
np.any([0, 0, 0])  # False
np.any([0, 1, 0])  # True

True

In [79]:
bool(0)  # False
bool(0.3)  # True

True

In [76]:
# ciekae funckje ze względów statystycznych
A = np.random.rand(5)  # z rokładu jednostajengo (0.1)
# np problem klasyfikacji mamy 5 klas, model zwrócił wartości prawdopodobieńst i cośbyśmy chcieli z tym dalej zrobić
print(A)  
print(np.argmax(A))  # indeks gdzie znajduej sie najwieszksza wartosc

[0.02010755 0.82894003 0.00469548 0.67781654 0.27000797]
1


In [77]:
# wycinanie elementu z tablicy
m = A[np.argmax(A)]

In [78]:
# .argmin - anlogicznie  indeks z najwmniejszą wartością
np.argmin(A)

2

In [81]:
# sortowanie - ale zqwraca INDEKSY w kolejnsoci
# przydatne gdy mamy klasyfikację wieloklasową i chcemy zwrócić 2 albo 3 najbardziej prawdopodobne klasy
print(np.argsort(A))# zwraca idensky w kolejnsoc gdzi eelemnty sa rosnące


[2 0 4 3 1]


In [81]:
# czysto statystuczne
np.max(A)  # wartosc

In [82]:
np.min(A)

0.004695476192547066

In [83]:
np.mean(A)  # średnia

0.36031351231715975

In [84]:
np.median(A)  # mediana

0.27000797319216485

In [85]:
np.std(A)  # odchylenie standardowe

0.33786931210140275

# 7. Indeksowanie wycinanie tablic

In [86]:
A = np.arange(20)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [87]:
# A[idx], A[start: stop], A[:stop], A[start:]
print(A[0])  # 0

0


In [88]:
print(A[5:10])  # [5 6 7 8 9]

[5 6 7 8 9]


In [89]:
print(A[:5])  # [0 1 2 3 4]

[0 1 2 3 4]


In [90]:
print(A[8:])  # [ 8  9 10 11 12 13 14 15 16 17 18 19]

[ 8  9 10 11 12 13 14 15 16 17 18 19]


In [91]:
print(A[-1])  # 19 ostatni element

19


In [93]:
# przekstałcenie
A = A.reshape(4, 5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [94]:
# konkrenty wiersza
print(A[0])  # pierwszy wiersz
print(A[1])

[0 1 2 3 4]
[5 6 7 8 9]


In [95]:
# wycinanie kolumny
print(A[:, 0])
print(A[:, -2])  # przeodstatnia
print(A[:, -1])


[ 0  5 10 15]
[ 3  8 13 18]
[ 4  9 14 19]


In [96]:
# konkrente położenie
print(A[1, 1])  # 6
print(A[1, 3])  # 8

6
8


In [97]:
# wyciannie fragmentu - środek tablicy
print(A[1:3, 1:4])

[[ 6  7  8]
 [11 12 13]]


In [98]:
# przypisanie nowych wartości do tablicy
print(A[1, 2])
A[1, 2] = 14
print(A)

7
[[ 0  1  2  3  4]
 [ 5  6 14  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# 8 Iteracja po tablicy

In [99]:
A = np.arange(20)
A = A.reshape(4, 5)
print(A[1, 2])
A[1, 2] = 14
print(A)

7
[[ 0  1  2  3  4]
 [ 5  6 14  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [100]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [101]:
for row in A:
    print(row[0])  # indeks zero z każdego wiersza


0
5
10
15


In [102]:
for row in A:
    print(row[:3])  # trzy peirwsze lementy

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [103]:
# .flat - wypłaszczenie tablicy
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [104]:
# Zmiana rozmairu tablicy
print(A.shape)

(4, 5)


In [106]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [105]:
# WYPLASZCZENIE DANYCH do 1D- odwrotna do operacji reshape
print(A.ravel())

[ 0  1  2  3  4  5  6 14  8  9 10 11 12 13 14 15 16 17 18 19]


In [107]:
# transponowanie tablicy tak samo jak macierzy
print(A.T)  # zamienia kolumny na wiereze

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2 14 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


MASKI LOGICZNE

In [108]:
# maski logiczne
M = np.arange(start=-10, stop=10, step=0.5)
M = M.reshape(10, -1)  # 0 wieerszy
print(M)

[[-10.   -9.5  -9.   -8.5]
 [ -8.   -7.5  -7.   -6.5]
 [ -6.   -5.5  -5.   -4.5]
 [ -4.   -3.5  -3.   -2.5]
 [ -2.   -1.5  -1.   -0.5]
 [  0.    0.5   1.    1.5]
 [  2.    2.5   3.    3.5]
 [  4.    4.5   5.    5.5]
 [  6.    6.5   7.    7.5]
 [  8.    8.5   9.    9.5]]


In [110]:
#  zastosowanie - chcemy się dowiedziec w których miejscach mamy wartości ujemne
print(M > 0)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [112]:
# dzięki masce jesteśmy w stanie wyciać dane który nas interesują
print(M[M > 0])

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.
 9.5]


In [114]:
# mozna łaczyć dwa warunki  - np konkrenty przedział
# tak zasotosować And nie można
# print(M[M > 5 and M < 5]) # ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [115]:
print(np.bitwise_and(M > -5, M < 5))

[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]
 [False False False False]]


In [116]:
print(M[np.bitwise_and(M > -5, M < 5)])  # Wycinanie elemntów które spełniają warunki

[-4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.
  2.5  3.   3.5  4.   4.5]


In [117]:
print(np.bitwise_or(M < -5, M > 5)) # maska

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [118]:
print(M[np.bitwise_or(M < -5, M > 5)]) # maska

[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5   5.5   6.
   6.5   7.    7.5   8.    8.5   9.    9.5]
